# create config.ini based on this file
[API]
BINANCE_HOST = Binance host
BINANCE_API_KEY = Binance api key
BINANCE_SECRET_KEY = Binance secret key
BYBIT_HOST = Bybit host
BYBIT_API_KEY = Bybit api key
BYBIT_SECRET_KEY = Bybit secret key